// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5JZ_3NS9sXTBsUx5CEpNIYggVmmKbMTU',
    appId: '1:46495509679:web:f19265177ea1656715385a',
    messagingSenderId: '46495509679',
    projectId: 'currency-app-5e71d',
    authDomain: 'currency-app-5e71d.firebaseapp.com',
    storageBucket: 'currency-app-5e71d.firebasestorage.app',
    measurementId: 'G-66S2KMVF4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPaHCuFfKa0htI6hnkAd2D0Q2k4YVcob8',
    appId: '1:46495509679:android:f88ce43e1f80599f15385a',
    messagingSenderId: '46495509679',
    projectId: 'currency-app-5e71d',
    storageBucket: 'currency-app-5e71d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2TtKOZpnCafVCyWBerwJ8U4Op3nIzdvA',
    appId: '1:46495509679:ios:27b03f8ca3cc24b615385a',
    messagingSenderId: '46495509679',
    projectId: 'currency-app-5e71d',
    storageBucket: 'currency-app-5e71d.firebasestorage.app',
    iosBundleId: 'com.example.currencyExchangeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2TtKOZpnCafVCyWBerwJ8U4Op3nIzdvA',
    appId: '1:46495509679:ios:27b03f8ca3cc24b615385a',
    messagingSenderId: '46495509679',
    projectId: 'currency-app-5e71d',
    storageBucket: 'currency-app-5e71d.firebasestorage.app',
    iosBundleId: 'com.example.currencyExchangeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5JZ_3NS9sXTBsUx5CEpNIYggVmmKbMTU',
    appId: '1:46495509679:web:d4c24fc968a8936715385a',
    messagingSenderId: '46495509679',
    projectId: 'currency-app-5e71d',
    authDomain: 'currency-app-5e71d.firebaseapp.com',
    storageBucket: 'currency-app-5e71d.firebasestorage.app',
    measurementId: 'G-850LQDLFQE',
  );
}
